version: '3.1'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    image: teste-mysql
    ports:
      - "3306:3306"
    container_name: teste-mysql
    networks: 
      app-network:
        aliases:
          - teste-mysql

  nodejs:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
    image: teste-nodejs
    container_name: teste-nodejs
    command: npm start
    depends_on: 
      - mysql
    links:
      - mysql
    networks: 
      app-network:
        aliases:
          - teste-nodejs

  nginx:
    image: nginx
    container_name: teste-nginx
    ports: 
      - "80:80"
    links:
      - nodejs
    networks: 
      app-network:
        aliases:
          - teste-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge